=== TymurNazarenko/CrazyHorseRacing/src/main/resources/schema/level_schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Level Schema",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "id",
    "maxPlayers",
    "imagePath",
    "horseSize",
    "initialRandomVelocity",
    "carrot",
    "spawnpoints",
    "walls"
  ],
  "properties": {
    "id": {
      "type": "integer",
      "minimum": 1
    },
    "maxPlayers": {
      "type": "integer",
      "minimum": 1
    },
    "imagePath": {
      "type": "string"
    },
    "horseSize": {
      "type": "number"
    },
    "initialRandomVelocity": {
      "type": "number"
    },
    "carrot": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/vec"
      }
    },
    "spawnpoints": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/vec"
      }
    },
    "walls": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/hitbox"
      }
    }
  },
  "$defs": {
    "vec": {
      "type": "array",
      "prefixItems": [
        {
          "type": "number"
        },
        {
          "type": "number"
        }
      ],
      "items": false,
      "minItems": 2,
      "maxItems": 2
    },
    "hitbox": {
      "type": "array",
      "minItems": 3,
      "items": {
        "$ref": "#/$defs/vec"
      }
    }
  }
}

=== TymurNazarenko/CrazyHorseRacing/src/main/resources/gamemaps/dangling.json
{
  "id": 2,
  "maxPlayers": 2,
  "imagePath": "/images/gamemap/dangling.jpg",
  "horseSize": 0.8,
  "initialRandomVelocity": 200.0,
  "carrot": [[442, 106], [485, 189], [527, 106]],
  "spawnpoints": [[81, 786], [223, 914]],
  "walls": [
	  [[1000, 22], [4, 20], [2, 3], [999, 1]],
	  [[3, 982], [999, 980], [1000, 1000], [5, 1000]],
	  [[984, 983], [981, 20], [1001, 23], [1001, 981]],
	  [[21, 21], [22, 982], [4, 981], [5, 20]],
	  [[23, 699], [783, 701], [783, 716], [22, 718]],
	  [[347, 411], [346, 435], [983, 442], [984, 409]],
	  [[22, 439], [48, 440], [48, 697], [26, 699]],
	  [[50, 462], [75, 465], [76, 698], [53, 699]],
	  [[80, 503], [112, 502], [115, 695], [88, 692]],
	  [[114, 547], [164, 546], [167, 697], [116, 697]],
	  [[164, 595], [243, 594], [244, 698], [164, 701]],
	  [[243, 652], [317, 655], [320, 700], [245, 697]],
	  [[447, 21], [410, 143], [424, 150], [460, 18]],
	  [[523, 20], [539, 146], [551, 146], [538, 20]],
	  [[418, 982], [419, 907], [439, 908], [441, 982]],
	  [[557, 912], [582, 911], [581, 983], [559, 983]],
	  [[391, 889], [391, 911], [608, 910], [608, 888]]
  ]
}

=== TymurNazarenko/CrazyHorseRacing/src/main/resources/gamemaps/minimaze.json
{
  "id": 1,
  "maxPlayers": 4,
  "imagePath": "/images/gamemap/minimaze.jpg",
  "horseSize": 1.0,
  "initialRandomVelocity": 200.0,
  "carrot": [[872, 810], [876, 927], [892, 929], [912, 812]],
  "spawnpoints": [[111, 107], [346, 122], [120, 249], [335, 257]],
  "walls": [
    [[1, 2], [999, 3], [1001, 44], [5, 43]],
    [[962, 43], [1000, 44], [1000, 999], [962, 1000]],
    [[2, 44], [40, 42], [41, 999], [4, 998]],
    [[39, 964], [965, 960], [970, 999], [40, 999]],
    [[182, 462], [276, 461], [276, 486], [181, 487]],
    [[605, 248], [625, 272], [760, 162], [745, 135]],
    [[42, 792], [229, 790], [230, 819], [42, 819]],
    [[498, 770], [499, 856], [524, 856], [524, 771]],
    [[433, 271], [433, 631], [459, 631], [458, 272]],
    [[751, 965], [750, 808], [775, 808], [777, 961]],
    [[432, 628], [435, 654], [771, 655], [770, 629]],
    [[962, 444], [964, 468], [756, 465], [757, 440]]
  ]
}

=== TymurNazarenko/CrazyHorseRacing/src/main/resources/gamemaps/garden.json
{
  "id": 3,
  "maxPlayers": 4,
  "imagePath": "/images/gamemap/garden.jpg",
  "horseSize": 0.9,
  "initialRandomVelocity": 60.0,
  "carrot": [[51, 528], [53, 580], [135, 568], [132, 533]],
  "spawnpoints": [[887, 98], [864, 301], [901, 906], [355, 103]],
  "walls": [
    [[1, 2], [2, 1001], [21, 1001], [22, 4]],
    [[982, 2], [983, 1000], [997, 1000], [998, 4]],
    [[23, 5], [983, 7], [984, 23], [22, 23]],
    [[21, 984], [983, 984], [982, 1000], [25, 1001]],
    [[681, 384], [811, 388], [808, 425], [686, 423]],
    [[452, 249], [502, 253], [500, 296], [453, 298]],
    [[583, 81], [576, 123], [621, 128], [624, 87]],
    [[198, 158], [192, 195], [231, 198], [234, 158]],
    [[332, 453], [327, 502], [371, 503], [373, 457]],
    [[70, 442], [73, 504], [130, 502], [129, 444]],
    [[500, 765], [498, 845], [572, 839], [569, 765]],
    [[863, 578], [864, 622], [903, 624], [902, 583]]
  ]
}
